name: Java8 Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 修改为JDK8环境
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build Project
      run: mvn -B clean package -DskipTests -DskipFront=true

    # Ruoyi项目JAR路径示例
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./ruoyi-admin/target/endless-manager.jar  # 精确匹配打包名称
        asset_name: ruoyi-admin-${{ steps.get-version.outputs.version }}.jar
