name: Endless Manager Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 代码检出
    - name: Checkout code
      uses: actions/checkout@v4

      # 设置Java8环境
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'

      # 构建项目
    - name: Build with Maven
      run: mvn -B clean package -DskipTests -DskipFront=true

      # 提取自定义版本号
    - name: Get Endless Version
      id: get-version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=endless.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 创建GitHub Release
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get-version.outputs.version }}
        release_name: Endless Manager v${{ steps.get-version.outputs.version }}
        draft: false
        prerelease: false

      # 上传JAR到Release
    - name: Upload JAR Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./ruoyi-admin/target/endless-manager-${{ steps.get-version.outputs.version }}.jar
        asset_name: endless-manager-${{ steps.get-version.outputs.version }}.jar

      # 可选：验证文件路径
    - name: Verify Build Output
      run: |
        echo "Generated JAR path:"
        ls -l ./ruoyi-admin/target/*.jar